### ISSUE TITLE
When I deploy this site from my github to Netlify and it does work. BUt when I try to login the page does not load its just a blank outline how can i fix this.

### ISSUE THREAD

**Issue by DEV0616** [eljn0/reactchatapp#1]
![image](https://user-images.githubusercontent.com/84785529/152872733-77e2ca6f-696d-458a-9859-6522ea4063ad.png)

**Comment by eljn0** [comment]
Hi, man how are you?
You have to link your project to chatengine.io.
If you want full explain watch this tutorial with my mate.(
https://youtu.be/jcOKU9f86XE)
Also there are some updates like sending voice and etc.
Hope, It will work!

8 fev 2022, Ç.a. tarixində 01:12 tarixində DEV0616 ***@***.***>
yazdı:
